export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';


export const FETCH_USERS_UPDATE_REQUEST = 'FETCH_USERS_UPDATE_REQUEST';
export const FETCH_USERS_UPDATE_SUCCESS = 'FETCH_USERS_UPDATE_SUCCESS';
export const FETCH_USERS_UPDATE_FAILURE = 'FETCH_USERS_UPDATE_FAILURE';

export const FETCH_USERS_DELETE_REQUEST = 'FETCH_USERS_DELETE_REQUEST';
export const FETCH_USERS_DELETE_SUCCESS = 'FETCH_USERS_DELETE_SUCCESS';
export const FETCH_USERS_DELETE_FAILURE = 'FETCH_USERS_DELETE_FAILURE';
